#!/bin/sh

cat () {
  eof=false
  until $eof ; do
    read -r line || eof=true 
    $eof && printf -- %s "$line" || printf -- %s\\n "$line"
  done
}

IFS=

[ $# = 0 ] && set -- -

while ! [ $# = 0 ] ; do
  if [ "$1" = - ] ; then
    cat
  else
    cat < "$1"
  fi
  shift
done
