#!/bin/sh

# bugs
# it ignores everything after the last newline

cat () {
  while read -r line ; do
    echo "$line"
  done
}

IFS=

[ $# = 0 ] && cat && exit

while ! [ $# = 0 ] ; do
  if [ "$1" = - ] ; then
    cat
  else
    cat < "$1"
  fi
  shift
done

